apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: marcelorocha/gitopsfc
  newTag: 2fc5bacce54553748229a185097d2817244bd5f2
